Repository fourseers/PartTimeJob, pull requests merged in 2019-07, with the labels that each got.

#102 Add iteration plan for r2.
  docs/iteration/r2/plan_r2.md
Labels: documentation

#123 Fea ci parallel tests
  .travis.yml
  code/backend/arrangement/pom.xml
  code/backend/arrangement/src/test/resources/application.properties
  code/backend/auth/src/test/resources/application.properties
  code/backend/pom.xml
  code/backend/warehouse/pom.xml
  code/backend/warehouse/src/test/resources/application.properties
Labels: enhancement

#128 travis auto deployment
  .travis.yml
  code/backend/auth/src/test/resources/application.properties
  deploy_conf.enc
  travis_id.enc
  travis_secrets.tar.enc
Labels: deployment

#135 add env secure vars
  .travis.yml
Labels: bug

#145 Refactor education column, represented as an enum in Java code now.
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/controller/JobController.java
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/service/impl/JobServiceImpl.java
  code/backend/arrangement/src/test/java/com/fourseers/parttimejob/arrangement/controller/JobControllerTest.java
  code/backend/arrangement/src/test/java/com/fourseers/parttimejob/arrangement/controller/WechatUserJobControllerTest.java
  code/backend/arrangement/src/test/resources/data.sql
  code/backend/auth/src/main/java/com/fourseers/parttimejob/auth/controller/WechatLoginController.java
  code/backend/auth/src/test/java/com/fourseers/parttimejob/auth/controller/WechatLoginControllerTest.java
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/CV.java
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/Etc.java
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/Job.java
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/WechatUser.java
  code/backend/warehouse/src/main/java/com/fourseers/parttimejob/warehouse/service/impl/WechatUserServiceImpl.java
  code/backend/warehouse/src/test/java/com/fourseers/parttimejob/warehouse/controller/WechatUserControllerTest.java
Labels: enhancement

#159 add doc for r2
  docs/iteration/r1/test_cases.xls
  docs/iteration/r2/burndown.png
  docs/iteration/r2/codebeat.png
  docs/iteration/r2/report_r2.md
  docs/iteration/r2/test_report.docx
Labels: documentation

#160 Set education column converter in CV
  code/backend/arrangement/src/test/resources/data.sql
  code/backend/billing/src/test/resources/data.sql
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/CV.java
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/Job.java
Labels: bug

#163 add iteration plan for r3
  docs/iteration/r3/plan_r3.md
Labels: documentation

#169 modify time plan & reduce workload
  docs/iteration/r3/plan_r3.md
Labels: documentation

#198 fix: #197
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/service/impl/ApplicationServiceImpl.java
Labels: bug

#211 change mysql timezone to CST
  code/backend/deploy.py
Labels: bug

#214 Fea es job recommendation
  code/backend/arrangement/pom.xml
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/config/AppConfig.java
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/controller/JobController.java
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/controller/WechatUserJobController.java
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/dto/SearchResultDto.java
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/service/JobService.java
  code/backend/arrangement/src/main/java/com/fourseers/parttimejob/arrangement/service/impl/JobServiceImpl.java
  code/backend/arrangement/src/main/resources/application.properties
  code/backend/arrangement/src/test/java/com/fourseers/parttimejob/arrangement/controller/WechatUserJobControllerTest.java
  code/backend/arrangement/src/test/resources/application.properties
  code/backend/common/pom.xml
  code/backend/common/src/main/java/com/fourseers/parttimejob/common/entity/Etc.java
  code/backend/pom.xml
Labels: enhancement
